export const ADD_FLASHCARD = "ADD_FLASHCARD";
export const UPDATE_FLASHCARD = "UPDATE_FLASHCARD";
export const REMOVE_FLASHCARD = "REMOVE_FLASHCARD";
export const CLICK_FLASHCARD = "CLICK_FLASHCARD";
export const CLICK_CARDSET = "CLICK_CARDSET";
export const ADD_CARDSET = "ADD_CARDSET";
export const UPDATE_CARDSET = "UPDATE_CARDSET";
export const REMOVE_CARDSET = "REMOVE_CARDSET";
